default: &default
  adapter: 'postgresql'
  encoding: 'unicode'
  host: <%= ENV.fetch('OSEM_DB_HOST', 'database') %>
  port: <%= ENV.fetch('OSEM_DB_PORT', '5432')  %>
  username: <%= ENV.fetch('OSEM_DB_USER', 'postgres') %>
  password: <%= ENV.fetch('OSEM_DB_PASSWORD', 'mysecretpassword') %>
  database: <%= ENV.fetch('OSEM_DB_NAME', 'postgres') %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: osem_development

test:
  <<: *default
  database: osem_test

production:
  <<: *default
